image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_TLS_CERTDIR: ""  # TLS 비활성화
  DOCKER_HOST: tcp://docker:2375  # TLS 없는 포트
  DOCKER_BUILDKIT: 1  # Docker BuildKit 활성화
  DOCKER_CLI_EXPERIMENTAL: enabled
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  DB_DATABASE: "homeblog"
  NODE_MODULES_CACHE_KEY: ${CI_COMMIT_REF_SLUG}-node-modules
  NODE_OPTIONS: "--max-old-space-size=4096"

cache:
  key: ${NODE_MODULES_CACHE_KEY}
  paths:
    - src/client/node_modules/
    - src/server/node_modules/
  policy: pull-push

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  parallel: 2
  script:
    - |
      if [ "$CI_NODE_INDEX" = "0" ]; then
        # 클라이언트 빌드
        docker build -t $CI_REGISTRY_IMAGE/client:$CI_COMMIT_SHA -f src/client/Dockerfile src/client/
        docker push $CI_REGISTRY_IMAGE/client:$CI_COMMIT_SHA
      else
        # 서버 빌드
        docker build -t $CI_REGISTRY_IMAGE/server:$CI_COMMIT_SHA -f src/server/Dockerfile src/server/
        docker push $CI_REGISTRY_IMAGE/server:$CI_COMMIT_SHA
      fi
  only:
    - main
    - develop
  tags:
    - blog
  timeout: 20m  # 타임아웃을 20분으로 증가

test:
  stage: test
  parallel: 2
  script:
    - |
      if [ "$CI_NODE_INDEX" = "0" ]; then
        cd src/client && npm install && npm run test
      else
        cd src/server && npm install && npm run test
      fi
  only:
    - main
    - develop
  tags:
    - blog

deploy:
  stage: deploy
  script:
    # NAS 배포 디렉토리로 이동
    - cd $NAS_DEPLOY_PATH
    # 환경 변수 파일 생성
    - |
      cat > .env << EOL
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE=${MYSQL_DATABASE}
      MYSQL_USER=${MYSQL_USER}
      MYSQL_PASSWORD=${MYSQL_PASSWORD}
      DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      NEXT_PUBLIC_API_URL=http://backend:4000
      EOL
    # 최신 이미지로 업데이트 (병렬 실행)
    - docker-compose -f docker-compose.yml pull client & docker-compose -f docker-compose.yml pull server & wait
    # 서비스 재시작
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose.yml up -d
  environment:
    name: production
  only:
    - main
  tags:
    - blog

deploy_staging:
  stage: deploy
  script:
    # NAS 배포 디렉토리로 이동
    - cd $NAS_DEPLOY_PATH
    # 환경 변수 파일 생성
    - |
      cat > .env << EOL
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE=${MYSQL_DATABASE}
      MYSQL_USER=${MYSQL_USER}
      MYSQL_PASSWORD=${MYSQL_PASSWORD}
      DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      NEXT_PUBLIC_API_URL=http://backend:4000
      EOL
    # 최신 이미지로 업데이트 (병렬 실행)
    - docker-compose -f docker-compose.yml pull client & docker-compose -f docker-compose.yml pull server & wait
    # 서비스 재시작
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose.yml up -d
  environment:
    name: staging
  only:
    - develop
  tags:
    - blog