image: node:20

# 환경설정
variables:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  DB_DATABASE: "homeblog"
  NODE_MODULES_CACHE_KEY: ${CI_COMMIT_REF_SLUG}-node-modules
  NODE_OPTIONS: "--max-old-space-size=4096"

# 캐쉬
cache:
  key: ${NODE_MODULES_CACHE_KEY}
  paths:
    - src/client/node_modules/
    - src/server/node_modules/
  policy: pull-push

# 순서
stages:
  - build
  - deploy

# 빌드
build:
  stage: build
  parallel: 2
  script:
    - |
      if [ "$CI_NODE_INDEX" = "0" ]; then
        # 클라이언트 빌드
        cd src/client
        npm install
        npm run build
      else
        # 서버 빌드
        cd src/server
        npm install
        npm run build
      fi
  only:
    - main
    - develop
  tags:
    - blog
  timeout: 20m

deploy:
  stage: deploy
  script:
    # PM2 설치
    - npm install -g pm2
    # NAS 배포 디렉토리로 이동
    - cd $NAS_DEPLOY_PATH
    # 환경 변수 파일 생성
    - |
      cat > .env << EOL
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE=${MYSQL_DATABASE}
      MYSQL_USER=${MYSQL_USER}
      MYSQL_PASSWORD=${MYSQL_PASSWORD}
      DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      NEXT_PUBLIC_API_URL=http://backend:4000
      EOL
    # 서비스 재시작
    - cd $CI_PROJECT_DIR/src/client && CI=false npm install && npm run build
    - cd $CI_PROJECT_DIR/src/server && npm install && npm run build
    - cd $CI_PROJECT_DIR
    - npm install -g serve
    - ls -la src/server/dist/
    - pm2 start src/server/dist/main.js --name "blog-server"
    - pm2 start "serve -s src/client/build -l 7000" --name "blog-client"
    - pm2 restart all
  environment:
    name: production
  only:
    - main
  tags:
    - blog

deploy_staging:
  stage: deploy
  script:
    # PM2 설치
    - npm install -g pm2
    # NAS 배포 디렉토리로 이동
    - cd $NAS_DEPLOY_PATH
    # 환경 변수 파일 생성
    - |
      cat > .env << EOL
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE=${MYSQL_DATABASE}
      MYSQL_USER=${MYSQL_USER}
      MYSQL_PASSWORD=${MYSQL_PASSWORD}
      DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      NEXT_PUBLIC_API_URL=http://backend:4000
      EOL
    # 서비스 재시작
    - cd $CI_PROJECT_DIR/src/client && CI=false npm install && npm run build
    - cd $CI_PROJECT_DIR/src/server && npm install && npm run build
    - cd $CI_PROJECT_DIR
    - npm install -g serve
    - ls -la src/server/dist/
    - pm2 start src/server/dist/main.js --name "blog-server"
    - pm2 start "serve -s src/client/build -l 7000" --name "blog-client"
    - pm2 restart all
  environment:
    name: staging
  only:
    - develop
  tags:
    - blog
