version: "3.8"

services:
  # NestJS 메인 API 서버
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=7000
      - DB_HOST=host.docker.internal
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE:-false}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    networks:
      - app-network
    restart: unless-stopped

  # WebSocket 채팅 서버
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - "7777:7777"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=7777
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
